[package]
name = "sound_themer"
version = "0.3.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.27.2", features = ["strum_macros", "derive"] }
thiserror = "2.0.18"
toml = "1.0.3"
