# Name of the selected sound theme
theme_name = "freedesktop"

[[themes]]
# Name of the sound theme folder
name = "freedesktop"

# Extension on the sound files
sound_ext = "oga"

# Directories where the sounds are found
directories = ["stereo"]

# Provide a mapping between certain phrases and their respective sound file name
[mapping]
audio-change = "audio-volume-change"
login = "service-login"
logout = "service-logout"
message = "message"
power-plug = "power-plug"
power-unplug = "power-unplug"

